// Mocks generated by Mockito 5.4.4 from annotations
// in sof_users/test/toggle_bookmark_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sof_users/data/repositories/bookmark_repository_impl.dart'
    as _i2;
import 'package:sof_users/data/repositories/user_repository_impl.dart' as _i3;
import 'package:sof_users/domain/model/user_model.dart' as _i6;
import 'package:sof_users/domain/response/sof_response.dart' as _i9;
import 'package:sof_users/domain/use_cases/get_list_bookmark_uc.dart' as _i7;
import 'package:sof_users/domain/use_cases/get_sof_user_uc.dart' as _i8;
import 'package:sof_users/domain/use_cases/toggle_bookmark_uc.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBookmarkRepositoryImpl_0 extends _i1.SmartFake
    implements _i2.BookmarkRepositoryImpl {
  _FakeBookmarkRepositoryImpl_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserRepositoryImpl_1 extends _i1.SmartFake
    implements _i3.UserRepositoryImpl {
  _FakeUserRepositoryImpl_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ToggleBookmarkUC].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleBookmarkUC extends _i1.Mock implements _i4.ToggleBookmarkUC {
  MockToggleBookmarkUC() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BookmarkRepositoryImpl get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeBookmarkRepositoryImpl_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.BookmarkRepositoryImpl);

  @override
  _i5.Future<bool> call({required _i6.UserModel? user}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#user: user},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [GetListBookmarkUC].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetListBookmarkUC extends _i1.Mock implements _i7.GetListBookmarkUC {
  MockGetListBookmarkUC() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BookmarkRepositoryImpl get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeBookmarkRepositoryImpl_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.BookmarkRepositoryImpl);

  @override
  _i5.Future<List<_i6.UserModel>> call({Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i5.Future<List<_i6.UserModel>>.value(<_i6.UserModel>[]),
      ) as _i5.Future<List<_i6.UserModel>>);
}

/// A class which mocks [GetSofUserUC].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSofUserUC extends _i1.Mock implements _i8.GetSofUserUC {
  MockGetSofUserUC() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UserRepositoryImpl get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserRepositoryImpl_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.UserRepositoryImpl);

  @override
  _i5.Future<_i9.SofResponse<List<_i6.UserModel>>?> call(
          {Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i5.Future<_i9.SofResponse<List<_i6.UserModel>>?>.value(),
      ) as _i5.Future<_i9.SofResponse<List<_i6.UserModel>>?>);
}
