name: sof_users
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  get_it: ^7.7.0
  flutter_screenutil: ^5.9.3
  bot_toast: ^4.1.3
  flutter_smart_dialog: ^4.9.8+2
  easy_localization: ^3.0.7
  logger: ^2.4.0
  flutter_dotenv: ^5.1.0
  dio: ^5.7.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  skeletonizer: ^1.4.2
  cached_network_image: ^3.4.1
  loading_animation_widget: ^1.2.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  hive_generator: ^2.0.1

  bloc: any
  meta: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  husky: ^0.1.7
  lint_staged: ^0.5.1
  commitlint_cli: ^0.7.1
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

lint_staged:
  "lib/**.dart": dart format --fix && dart fix --apply

flutter:
  uses-material-design: true
  assets:
    - lib/core/translations/
    - assets/imgs/
    - assets/icons/
    - .env
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
